export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_PEDNDING = "LOGIN_PEDNDING";
export const USER_DATA_GET_SUCCESSFULLY = "USER_DATA_GET_SUCCESSFULLY";
